{
 "title": "Zeek Dashboard",
 "time": { "from": "2024-02-17T17:05:00.899Z", "to": "2024-02-17T17:07:54.003Z" },
 "panels": [
  {
   "title": "DNS Queries",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT \n  query, COUNT(*) as count\nFROM dns  \nWHERE ts >= $__from / 1000 AND ts < $__to / 1000\nGROUP BY query\nORDER BY count DESC\nLIMIT 30",
     "rawQueryText": "SELECT \n  query, COUNT(*) as count\nFROM dns  \nWHERE ts >= $__from / 1000 AND ts < $__to / 1000\nGROUP BY query\nORDER BY count DESC\nLIMIT 30",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "HTTP Hosts",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT \n  host, COUNT(*) as count\nFROM http  \nWHERE ts >= $__from / 1000 AND ts < $__to / 1000\nGROUP BY host\nORDER BY count DESC\nLIMIT 30\n",
     "rawQueryText": "SELECT \n  host, COUNT(*) as count\nFROM http  \nWHERE ts >= $__from / 1000 AND ts < $__to / 1000\nGROUP BY host\nORDER BY count DESC\nLIMIT 30\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SSL Server Name",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT \n  server_name, COUNT(*) as count\nFROM ssl  \nWHERE ts >= $__from / 1000 AND ts < $__to / 1000\nGROUP BY server_name\nORDER BY count DESC\nLIMIT 30",
     "rawQueryText": "SELECT \n  server_name, COUNT(*) as count\nFROM ssl  \nWHERE ts >= $__from / 1000 AND ts < $__to / 1000\nGROUP BY server_name\nORDER BY count DESC\nLIMIT 30",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Remote Connections",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT `geo_resp_latitude` AS latitude, `geo_resp_longitude` AS longitude, count(*) as count\nFROM conn\nGROUP BY `geo_resp_latitude`, `geo_resp_longitude`",
     "rawQueryText": "SELECT `geo_resp_latitude` AS latitude, `geo_resp_longitude` AS longitude, count(*) as count\nFROM conn\nGROUP BY `geo_resp_latitude`, `geo_resp_longitude`",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Node Connections",
   "type": "nodeGraph",
   "gridPos": { "h": 19, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "queryText": "SELECT DISTINCT id_orig_h AS id,                                                                                                                               \nid_orig_h AS source,                                                                                                                                           \nid_resp_h AS target                                                                                                                       \nFROM conn                                                                                                                                          \nWHERE ts >= $__from / 1000 and ts < $__to / 1000;  ",
     "rawQueryText": "SELECT DISTINCT id_orig_h AS id,                                                                                                                               \nid_orig_h AS source,                                                                                                                                           \nid_resp_h AS target                                                                                                                       \nFROM conn                                                                                                                                          \nWHERE ts >= $__from / 1000 and ts < $__to / 1000;  ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Connections / 5 sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "queryText": "SELECT \n  (ROUND(ts / 5) * 5) AS time, \n  COUNT(*) AS \"value\"\nFROM \n  conn\nWHERE \n  ts >= $__from / 1000 AND \n  ts < $__to / 1000\nGROUP BY \n  time\nORDER BY \n  time ASC\n",
     "rawQueryText": "SELECT \n  (ROUND(ts / 5) * 5) AS time, \n  COUNT(*) AS \"value\"\nFROM \n  conn\nWHERE \n  ts >= $__from / 1000 AND \n  ts < $__to / 1000\nGROUP BY \n  time\nORDER BY \n  time ASC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Outgoing Bytes / host",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT                                                                                                                \n  id_orig_h,                                                                                                          \n  sum(orig_bytes) AS total_orig_bytes                                                                                 \nFROM conn                                                                                                             \nWHERE ts >= ($__from / 1000) AND ts < ($__to / 1000)                                                                  \nGROUP BY id_orig_h                                                                                                    \nORDER BY total_orig_bytes DESC                                                                                        \nLIMIT 20;     ",
     "rawQueryText": "SELECT                                                                                                                \n  id_orig_h,                                                                                                          \n  sum(orig_bytes) AS total_orig_bytes                                                                                 \nFROM conn                                                                                                             \nWHERE ts >= ($__from / 1000) AND ts < ($__to / 1000)                                                                  \nGROUP BY id_orig_h                                                                                                    \nORDER BY total_orig_bytes DESC                                                                                        \nLIMIT 20;     ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Incoming Bytes / host",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT                                                                                                                \n  id_resp_h,                                                                                                       \n  sum(resp_bytes) AS total_resp_bytes                                                                                 \nFROM conn                                                                                                             \nWHERE ts >= ($__from / 1000) AND ts < ($__to / 1000)                                                                  \nGROUP BY id_resp_h                                                                                                    \nORDER BY total_resp_bytes DESC                                                                                        \nLIMIT 20;     ",
     "rawQueryText": "SELECT                                                                                                                \n  id_resp_h,                                                                                                       \n  sum(resp_bytes) AS total_resp_bytes                                                                                 \nFROM conn                                                                                                             \nWHERE ts >= ($__from / 1000) AND ts < ($__to / 1000)                                                                  \nGROUP BY id_resp_h                                                                                                    \nORDER BY total_resp_bytes DESC                                                                                        \nLIMIT 20;     ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Connections / Port / Geo / Bytes",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 22 },
   "targets": [
    {
     "queryText": "SELECT id_orig_h, id_resp_h, id_resp_p, geo_resp_country_code, SUM(orig_bytes) as total_orig, SUM(resp_bytes) as total_resp                                                                                                \nFROM conn                                                                                                                                                      \nWHERE ts >= $__from / 1000 and ts < $__to / 1000                                                                                                               \nGROUP BY id_orig_h, id_resp_h                                                                                                                                  \nORDER BY total_resp DESC   ",
     "rawQueryText": "SELECT id_orig_h, id_resp_h, id_resp_p, geo_resp_country_code, SUM(orig_bytes) as total_orig, SUM(resp_bytes) as total_resp                                                                                                \nFROM conn                                                                                                                                                      \nWHERE ts >= $__from / 1000 and ts < $__to / 1000                                                                                                               \nGROUP BY id_orig_h, id_resp_h                                                                                                                                  \nORDER BY total_resp DESC   ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Bytes Transfered / Host",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "queryText": "SELECT id_orig_h, id_resp_h, SUM(orig_bytes) as total_orig, SUM(resp_bytes) as total_resp                                                                                                \nFROM conn                                                                                                                                                      \nWHERE ts >= $__from / 1000 and ts < $__to / 1000                                                                                                               \nGROUP BY id_orig_h, id_resp_h                                                                                                                                  \nORDER BY total_resp DESC\nLIMIT 30        ",
     "rawQueryText": "SELECT id_orig_h, id_resp_h, SUM(orig_bytes) as total_orig, SUM(resp_bytes) as total_resp                                                                                                \nFROM conn                                                                                                                                                      \nWHERE ts >= $__from / 1000 and ts < $__to / 1000                                                                                                               \nGROUP BY id_orig_h, id_resp_h                                                                                                                                  \nORDER BY total_resp DESC\nLIMIT 30        ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "SSL Subject / Issuer",
   "type": "table",
   "gridPos": { "h": 16, "w": 18, "x": 6, "y": 30 },
   "targets": [
    {
     "queryText": "SELECT \n  certificate_subject, certificate_issuer, COUNT(*) as count\nFROM x509  \nWHERE ts >= $__from / 1000 AND ts < $__to / 1000\nGROUP BY certificate_issuer\nORDER BY count DESC\n",
     "rawQueryText": "SELECT \n  certificate_subject, certificate_issuer, COUNT(*) as count\nFROM x509  \nWHERE ts >= $__from / 1000 AND ts < $__to / 1000\nGROUP BY certificate_issuer\nORDER BY count DESC\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}